Increment13
TheMadman48L/shortener pull request #12
Opened 2022-10-27 15:56 UTC by TheMadman48L

2022-10-31 19:45 UTC, lostsequence requested changes

2022-10-31 19:45 UTC, lostsequence commented on internal/handlers/middleware/middleware.go
> +}
Если будет несколько запросов подряд одновременно, какое значение будет в итоге в поле ?
Безопасней передать юзер id  в контекст реквеста, например.

2022-10-31 19:45 UTC, lostsequence commented on internal/storage/pgstore.go
> +	conn *pgx.Conn
лучше использовать connection pool (pgxpool), pgx не потокобезопасен

2022-10-31 19:45 UTC, lostsequence commented on internal/shortener/shortener.go
> +	}
Добавь, пожалуйста, новый метод в стор, который будет выполнять сохранение урлов.
Если делать в цикле - то надо добавить транзакцию, чтобы откатить все изменения, если что-то не сохранится.
Второй вариант - объединить все значения в values и одним запросом вставить все значения.

2022-10-31 19:45 UTC, lostsequence commented on internal/handlers/handlers.go
> +	}
Рассмотри вариант с NewEncoder(), NewDecoder()

2022-10-31 19:45 UTC, lostsequence commented on internal/storage/pgstore.go
> +	ps, err := pgx.Connect(context.Background(), dsn)
Лучше пустой контекст не использовать, можно создать с тайм-аутом
Но уже вне функции-конструктора

2022-10-31 19:45 UTC, lostsequence commented on internal/storage/pgstore.go
> +	}, nil
Не нашел где закрывается коннекшн к базе.
Надо закрыть в мейне (там где и создаем)

2022-10-31 19:45 UTC, lostsequence commented on internal/storage/storage.go
> +	// return slowpokestore.NewSlowpokeStore(cfg.FileNameSlowpoke), nil
Не очень понял со slowpoke на проде )

2022-10-31 19:45 UTC, lostsequence commented on internal/handlers/handlers_test.go
> +	r.Use(h.Middleware.CookieHandle)
Можно потестить gzip и куки

2022-11-01 20:47 UTC, TheMadman48L commented on internal/storage/pgstore.go
> +	conn *pgx.Conn
исправил

2022-11-01 20:47 UTC, TheMadman48L commented on internal/handlers/middleware/middleware.go
> +			fmt.Printf("error: %v\n", err)
заменил

2022-11-01 21:05 UTC, TheMadman48L commented on internal/storage/pgstore.go
> +	ps, err := pgx.Connect(context.Background(), dsn)
+

2022-11-01 21:05 UTC, TheMadman48L commented on internal/storage/pgstore.go
> +	}, nil
+

2022-11-01 21:06 UTC, TheMadman48L commented on internal/storage/storage.go
> +	// return slowpokestore.NewSlowpokeStore(cfg.FileNameSlowpoke), nil
+

2022-11-02 00:00 UTC, TheMadman48L commented on internal/handlers/middleware/middleware.go
> +}
ok

2022-11-02 00:00 UTC, TheMadman48L commented on internal/handlers/middleware/middleware.go
> +}
ok

2022-11-02 00:42 UTC, TheMadman48L commented on internal/handlers/handlers.go
> +	}
ok

2022-11-02 07:19 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +	}
ok

2022-11-02 07:22 UTC, TheMadman48L commented on internal/handlers/handlers_test.go
> +	r.Use(h.Middleware.CookieHandle)
с тестами пока на самом деле всё очень плохо, не разобрался нормально. 
в рамках 4 спринта постарась исправить. 
хотел позже их на 1-1 обсудить

2022-11-07 10:30 UTC, lostsequence approved these changes

2022-11-07 20:05 UTC, merged