Increment3
TheMadman48L/shortener pull request #2
Opened 2022-07-16 20:09 UTC by TheMadman48L

пока тесты по минимуму, не понял пока до конца тестирование http сервиса и моки...

2022-07-19 17:39 UTC, capsulated commented
В принципе всё ок, но, желательно, немного реорганизовать сущности: пакеты, структуры, интерфейсы. Немного совсем порядок навести с неймингом структур/интерфейсов и пакетов. Вложенность пакетов делать не нужно, достаточно в одном пакете несколько файлов с одной/несколькими структурами и конструкторами. А можно и по пакетам разбить.

Так как бизнес логика в этом задании простая, вложенные пакеты здесь только усложнят историю, но, в принципе, тоже возможно, если они не будут мешать чтению кода.

2022-07-19 17:40 UTC, capsulated requested changes
В принципе всё ок, но, желательно, немного реорганизовать сущности: пакеты, структуры, интерфейсы. Немного совсем порядок навести с неймингом структур/интерфейсов и пакетов. Вложенность пакетов делать не нужно, достаточно в одном пакете несколько файлов с одной/несколькими структурами и конструкторами. Так как бизнес логика в этом задании простая, вложенные пакеты здесь только усложнят историю, но, в принципе, тоже возможно, если они не будут мешать чтению кода.

2022-07-19 17:40 UTC, capsulated commented on cmd/shortener/main.go
> +	rep, err := repo.New(&repo.Options{Env: "dev"})
По неймингу дам **рекомендацию**: пакеты лучше называть так, чтобы сразу было понятно, что он делает. В нашем случае app, repo и service неоднозначно отражают их суть. 

Для читаемости, хорошо делать минимальную вложенность пакетов, и добавлять только там, где это действительно необходимо.

Скажем, options лучше сделать отдельной структурой, и даже назвать config.

В общем, именно в этом задании, достаточно одной папки internal, а в ней несколько структур с интерфейсами по файлам распределить:
-internal
--config.go
--shortener.go (можно поделить на server.go и shortener.go)
--slowpoke_store.go
--map_sotore.go

В каждом структура, (может быть) интерфейс, и конструктор. Сообщество рекомендует именовать NewИмяСтурктуры():  NewShortener(), NewSlowpokeStore(), NewMapStore() и т.п.

2022-07-19 17:40 UTC, capsulated commented on cmd/shortener/main.go
> +	rep, err := repo.New(&repo.Options{Env: "dev"})
А возвращать конструктор должен указатель на структуру.

В большинстве случаев лучше работать с указателями. Это касается структур и любых больших объектов, для предотвращения копирования и выделения памяти при передачи в параметрах. 

Соответсвенно, в параметрах также использовать указатели.

Подробнее тут: 
https://medium.com/@drandin/%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D0%B8-%D0%B2-golang-27a5d70ef141

2022-07-19 17:40 UTC, capsulated commented on internal/app/app.go
> +type app struct {
Тут скорее server, в нём конструктор NewServer() и в конструкторе создание роутов. Так же, метод для структуры (s *Server) Run(), в котором ListenAndServe().

Это пример. Подумайте, как организовать сущности и как обозвать их более однозначно.

В коде присутствует интерфейс Shortener, но структура app. Интерфейс очень удобно описывать перед структурой, которая его наследует, тогда будет легче прочитать, что к чему относится.

В итоге получается, что service наследует Shortener, а Repo наследуют Storage и slowpocke. Лучше, если они отличались например: MapStore и SlowPockeStore структуры с интерфейсом Storer.

https://go.dev/doc/effective_go#interface-names

2022-07-21 06:18 UTC, TheMadman48L commented on cmd/shortener/main.go
> +	rep, err := repo.New(&repo.Options{Env: "dev"})
немного переделал, но есть сомнения что не так понял

2022-07-21 06:22 UTC, TheMadman48L commented on internal/app/app.go
> +type app struct {
изменил наименования

насчёт интерфейс описывать перед структурой которая его наследует, вроде так и было сделано.... запутался немного, начал интерфейсы выносить в те файлы/пакеты где они описаны, но потом подумал что это совсем не то

2022-07-21 06:24 UTC, TheMadman48L commented on cmd/shortener/main.go
> +	rep, err := repo.New(&repo.Options{Env: "dev"})
с этим вроде разобрался

2022-07-21 14:23 UTC, capsulated requested changes
Необходимо немного пофиксить нейминг интерфейсов и разобраться с использованием указателей или экземпляров в функциях структур.

В остальном всё хорошо, на сущности классно декомпозированы объекты: Server, Shortener, Storage, интерфейсы правильно используются, конструкторы и их имена. 👍

2022-07-21 14:23 UTC, capsulated commented on internal/shortener/shortener.go
> +func NewShortener(store Storage) *shortener {
Здесь также, можно структуру назвать типа ShortService или ShortLink или ещё как-то, чтобы интерфейс был S(s)hortener. Это всё для читабельности.

**Небольшое отступление**: мне самому нравится вообще формат, который отличается от рекомендаций комьюнити:
- type Shortener struct {...} - это сам объект (класс/сущность)
- type Shorting interface {...} - интерфейс
- func (s *Shortener) ShortUrl {...} - метода

Но, повторюсь, сообществом рекомендовано по-другому: https://go.dev/doc/effective_go#interface-names И на данном этапе обучения лучше придерживаться практик, а после обучения можно и экспериментировать)

2022-07-21 14:23 UTC, capsulated commented on internal/shortener/shortener.go
> +const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Тут уже по-желанию, просто делюсь своими мыслями: я бы в саму структуру добавил поле letterBytes и заполнял в конструкторе. Но это совсем не обязательно! Кому как удобнее)

2022-07-21 14:23 UTC, capsulated commented on internal/shortener/shortener.go
> +func (s *shortener) checkKey(hash string) bool {
Тут также мысли об уровнях абстракции: проверку можно и не выносить в отдельную функцию. Если она используется в нескольких местах, тогда это обязательная практика: не повторяться (принцип DRY).

2022-07-21 14:23 UTC, capsulated commented on internal/storage/slowpoke_store.go
> +func NewSlowpokeStore() *slowpokeStore {
Тут **можно** интерфейс возвращать в конструкторе. А можно и указатель) В нашем примере разницы нет, но строгость кода немного увеличивается, а при изменениях структуры будет нагляднее видно, что нарушено соответствие интерфейсу на уровне конструктора, а не позже - на уровне передачи созданной структуры в параметрах.

2022-07-22 05:51 UTC, TheMadman48L commented on internal/app/app.go
> +	_, err = w.Write([]byte("http://localhost:" + Port + "/" + hash))
тут согласен, но я так и [сделал](https://github.com/TheMadman48L/shortener/blob/increment3/internal/server/server.go#L63)) вы здесь ссылаетесь на файл которого уже нет в коммите

в конфиг пока решил не выносить ничего, по темам вроде там это дальше ещё будет разбираться насколько я понял

2022-07-22 05:51 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +type Storage interface {
ок

2022-07-22 05:52 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +	store Storage
ок

2022-07-22 05:54 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +func NewShortener(store Storage) *shortener {
ок
по поводу добавления -er, насколько я понял это рекомендуют делать только для однометодных интерфейсов типа Reader где кроме схожего по названию метода Read нет ничего, поэтому изначально и не стал делать Shortener так как у меня там уже два метода и названия другие

2022-07-22 05:58 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +func (s *shortener) checkKey(hash string) bool {
согласен что если кусок кода не большой и используется один раз то выносить в отдельную функцию избыточно.
но тут у меня результат проверки используется в цикле и не сразу придумал как можно сделать это не вынося в отдельную функцию. оказалось просто всё)

2022-07-22 05:58 UTC, TheMadman48L commented on internal/shortener/shortener.go
> +const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
ок

2022-07-22 06:00 UTC, TheMadman48L commented on internal/storage/slowpoke_store.go
> +func (s slowpokeStore) Get(hash string) (string, error) {
тут что-то упустил изначально, желательно использовать указатель
чтоб не копировать каждый раз структуру, а передавать только ссылку на уже созданную
и так же при передаче по указателю в случае модификации структуры мы не возвращаем результат - новую структуру, а меняем по ссылке исходную

2022-07-22 06:08 UTC, TheMadman48L commented on cmd/shortener/main.go
> +	store := storage.NewSlowpokeStore()
вот тут ничего не стал менять
не до конца разобрался с интерфейсами, почитаю ещё статьи и потом на 1to1 вопросы позадаю))

я попробовал возвращать интерфейс Storager в конструторе NewSlowpokeStore()
но так как интерфейс описан в файле/пакете shortener то получается мне необходимо импортировать этот пакет? всё правильно понял или не то что-то?

2022-07-22 06:09 UTC, TheMadman48L commented on internal/storage/slowpoke_store.go
> +func NewSlowpokeStore() *slowpokeStore {
выше про это расписал подробнее, пока не переделал

2022-07-22 09:02 UTC, capsulated commented on cmd/shortener/main.go
> +	store := storage.NewSlowpokeStore()
Да, всё верно. Везде, где используется интерфейс, если он не в этом же пакете, то его нужно импортировать.

2022-07-23 17:04 UTC, capsulated requested changes
Чтение аргумента командной строки (флаг) обязательно перенести в cmd. 

Остальные комментарии прочитать. Биндинг роутера желательно перенести, но если есть какой-то смысл в назначении роутов при старте сервера (а не в конструкторе), то оставить комментарий по этому поводу.

Остальное - всё супер! 👍

2022-07-28 14:02 UTC, TheMadman48L commented on internal/server/server.go
> +	s.r.HandleFunc("/", s.handleShortingURL).Methods("POST")
перенес

2022-07-28 17:57 UTC, capsulated commented
Ок)

2022-07-28 17:57 UTC, merged